[libraries]

lib.files = [
"CodingConvention.vhdl",
"packages\\constant_package.vhdl",
"packages\\type_packages.vhdl",
"testbenches\\register\\PipelineRegister_tb.vhdl",
"testbenches\\alu\\my_alu_tb.vhdl",
"testbenches\\multiplexer\\gen_mux_tb.vhdl",
"testbenches\\registerfile\\register_file_tb.vhdl",
"components\\register\\PipelineRegister.vhdl",
"components\\alu\\my_gen_xor.vhdl",
"components\\alu\\my_alu.vhdl",
"components\\alu\\my_half_adder.vhdl",
"components\\alu\\my_gen_n_bit_full_adder.vhdl",
"components\\alu\\my_gen_or.vhdl",
"components\\alu\\my_shifter.vhdl",
"components\\alu\\my_full_adder.vhdl",
"components\\alu\\my_gen_and.vhdl",
"components\\multiplexer\\gen_mux.vhdl",
"components\\registerfile\\register_file.vhdl",
"components\\registerfile\\constant_package.vhdl",
"components\\registerfile\\type_packages.vhdl",
]
